# Experimental - detection of auto fishing mods based on movement
autoFishDetection: true

# Use & for format codes
messages:
  # For admin messages
  messagePrefix: "&8[&bAqua&8] "

  afkForPlayer: "&cAFK rybolov není na tomto serveru povolen"
  # %p% %u% placeholders for username and uuid required
  afkForAdmin: "&3Zjištěný hráč &a%p%&3 že použiva &a AFK Rybářský stroj"

  autoForPlayer: "&aNa tomto serveru není povolen automatický rybolov"
  # %p% %u% placeholders for username and uuid required
  autoForAdmin: "&3vykopnutý hráč &a%p%&3 pro &aAuto Fishing \n&3 UUID: (%u%)"